### ISSUE TITLE
cmake 오류 관련 (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by mochafreddo** [kakao/khaiii#103]
참고 : [[Khaiii] Installation on Ubuntu 20.04LTS](https://yoonchanheee.wordpress.com/2020/07/08/khaiii-installation-on-ubuntu-20-04lts/)

**Comment by krikit** [comment]
@mochafreddo 링크가 열리지 않아요..

**Comment by krikit** [comment]
위 링크 페이지가 열릴때도 있고 안열릴 때도 있고 그러네요.
Ubuntu 20.04에서 빌드를 지원하기 위해 v0.5를 준비 중에 있습니다.
말씀하신 내용을 참고하도록 하겠습니다. 감사합니다.
