### ISSUE TITLE
[Ubuntu] ImportError: No module named khaiii

### ISSUE THREAD

**Issue by LeeNajeong** [kakao/khaiii#107]
안녕하세요,

khaiii 설치를 마치고 python과 바인딩도 끝낸 상태입니다.

쉘 스크립트 'format_data.sh' 내에서 khaiii가 포함된 'proc_ko.py' 를 실행시키는 프로그램을 만들었습니다.

proc_ko.py 를 독립적으로 실행시켰을때는 문제가 없었던 반면에 
쉘 스크립트를 실행하여 proc_ko.py 가 실행될때는 아래 오류가 발생합니다.

**Traceback (most recent call last):
    File "media/sf_projet/pe/pe/PROGRAMME/SCRIPTS/proc_ko.py", line 5, in <module>
       from khaiii import KhaiiiApi  
ImportError: No module named khaiii**

format_data.sh

`#!/bin/bash`
`python path/to/python/file/proc_ko.py`

proc_ko.py 

`from khaiii import KhaiiiApi`
`api = KhaiiiApi()`

인터넷 서칭을 해도 그렇다 할 해답을 얻지 못해 도움 부탁드립니다.

**Comment by krikit** [comment]
위키의 [설치 위치에 관하여](https://github.com/kakao/khaiii/wiki/%EC%84%A4%EC%B9%98-%EC%9C%84%EC%B9%98%EC%97%90-%EA%B4%80%ED%95%98%EC%97%AC) 문서를 확인해 보시기 바랍니다.
`libkhaiii.so` 파일과 `khaiii.py` 파일이 어디에 설치되는지, khaiii를 임포트하여 사용하는 python 프로그램의 위치가 어딘지, `PYTHONPATH` 환경변수는 어떻게 설정하시는지에 따라 다를 것으로 생각합니다.
