### ISSUE TITLE
khaiii 사전 추가시 오류

### ISSUE THREAD

**Issue by kjihyun** [kakao/khaiii#111]
<img width="751" alt="스크린샷 2022-10-27 오전 11 27 44" src="https://user-images.githubusercontent.com/41855415/198176477-59307515-4de1-4318-8fc3-fd434891e126.png">

기분석 사전의 포맷은 <어절(패턴)> <탭> <분석 결과> 이대로 넣었는데요.. (mac 입니다)
위와같이 에러가뜨는건 어떤것 때문인가요?ㅠㅠ

**Comment by krikit** [comment]
"시그니처*"와 "시그니처/NNP" 사이에 탭이 아니라 공백이 들어간 것은 아닌가요?

**Comment by kjihyun** [comment]
탭으로 입력하였습니다..ㅠㅠ
