### ISSUE TITLE
Change default branch to develop

### ISSUE THREAD

**Issue by cynthia** [kakao/khaiii#17]
Based on the guidelines posted, it seems like it would be sensible to change GH’s project settings to have the default branch as develop.

In the build instructions you can point the users to checkout the master branch to make it the stable branch. This is strange, but considering most people just copy and paste build instructions this shouldn’t be that much extra work on the user’s end.

This isn’t optimal, but otherwise you’ll end up with PRs constantly being thrown against master - the unfortunate reality is that **people do not read documentation carefully** so preventing human errors systematically is easier.

A long term solution would be to have Travis CI triggers for lint/build/test so PRs have that information.

**Comment by krikit** [comment]
Right! The concern what you have is also ours. Khaiii is just born. :) We are preparing pull request template, CI and other automated stuffs.

**Comment by cynthia** [comment]
Do you need any help with this? I happen to have some experience with large open source projects.

**Comment by krikit** [comment]
Sure. I just made a [slack team](https://khaiii.slack.com). Would you join?

**Comment by cynthia** [comment]
Sure, send me an invite. My mail address should be visible through the git history.
