### ISSUE TITLE
doc 디렉토리의 내용을 docs로 이동

### ISSUE THREAD

**Issue by krikit** [kakao/khaiii#19]
pull request 템플릿은 `docs` 디렉토리 아래에 있어야 적용이 됩니다. 덕분에 `doc`, `docs` 두개의 디렉토리가 되어 버렸는데, `doc` 아래의 내용을 `docs`로 이동하고 `doc` 디렉토리를 삭제합니다.

**Comment by kkweon** [comment]
PULL REQUEST TEMPLATE 파일은 보통 `.github/`에 저장하는데
그러면 일반적으로 Hidden 상태라 더 깔끔한 것 같습니다. 
docs로 옮길 필요도 없어지구요.

## Example

https://github.com/Kitware/CMake/tree/master/.github
