### ISSUE TITLE
테스트 질문 : 디렉토리 디/NNG + 렉터리/NNG

### ISSUE THREAD

**Issue by j2doll** [kakao/khaiii#2]
:one: 다음과 같은 빌드 설명서에 있는 문장을 실행해 보았습니다.
```
실행 프로그램과 리소스가 준비되면 build 디렉터리 아래에서 다음과 같이 실행해 봅니다.
```

:two: 결과는 다음과 같습니다.
```
실행    실행/NNG
프로그램과      프로그램/NNG + 과/JC
리소스가        리소스/NNP + 가/JKS
준비되면        준비/NNG + 되/XSV + 면/EC
build   build/SL
디렉터리        디/NNG + 렉터리/NNG
아래에서        아래/NNG + 에서/JKB
다음과  다음/NNG + 과/JKB
같이    같이/MAG
실행해  실행/NNG + 하/XSV + 여/EC
봅니다. 보/VX + ㅂ니다/EF + ./SF
```

❓ 디렉토리가 디/NNG + 렉터리/NNG 로 분석되는 것이 맞나요?

**Comment by krikit** [comment]
형태소 분석기는 필연적으로 오분석이 나타나게 됩니다. 말씀하신 "디렉터리"가 "디/NNG + 렉터리/NNG"로 분석되는 것은 **정상 동작**이지만 그 내용은 **오분석**입니다.

이러한 오분석이 나타나는 이유는 학습 코퍼스의 부족일 수도 있고, 기계학습 알고리즘의 한계일 수도 있습니다.

속도를 포기하더라도 오분석을 조금이라도 줄이기 위해서는 large 모델을 빌드해 보시는 것을 추천 드립니다. 아래와 같이 리소스를 빌드하시면 됩니다.

```
make large_resource
```

large 모델을 사용한 결과는 아래와 같습니다.

```
실행	실행/NNG
프로그램과	프로그램/NNG + 과/JC
리소스가	리소스/NNP + 가/JKS
준비되면	준비/NNG + 되/XSV + 면/EC
build	build/SL
디렉터리	디렉터리/NNG
아래에서	아래/NNG + 에서/JKB
다음과	다음/NNG + 과/JKB
같이	같이/MAG
실행해	실행/NNG + 하/XSV + 여/EC
봅니다.	보/VX + ㅂ니다/EF + ./SF
```

혹은, base 모델 사전을 그대로 사용하시고, 기분석 사전에 "디렉터리* \t 디렉터리/NNG"와 같이 넣는 방법도 있습니다. rsc/src/preanal.manual 파일에 추가한 다음 리소스를 다시 빌드하시면 됩니다.

**Comment by j2doll** [comment]
:one: 설명해주신 대로 하니 잘 됩니다. 👍 
:two: 그런데  rsc/src/preanal.manual 에 내용을 추가하면 매번 make resource 를 해야 하나요?

**Comment by krikit** [comment]
네, 항상 `make resource` 하셔야 합니다.

소스 코드를 빌드하여 바이너리 프로그램을 생성하듯이, rsc/src 디렉토리 아래의 사전 소스를 빌드하여 build/share/khaiii 디렉토리 아래의 리소스를 생성합니다.
