### ISSUE TITLE
hunter 파일을 다운받는데 오류가 발생합니다.

### ISSUE THREAD

**Issue by gjustin40** [kakao/khaiii#21]
bulid 폴더 안에서 cmake ..을 실행했을 때 이러한 오류가 발생합니다.
제가 컴퓨터 전공은 아니라서 제 작업 환경이 이게 맞는지 모르겠지만
GCP vm을 이용하고 있고 ubuntu 16.x 에서 실행했습니다.

-- [hunter] Initializing Hunter workspace (70287b1ffa810ee4e952052a9adff9b4856d0d54)
-- [hunter]   https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz
-- [hunter]   -> /home/SAMSUNG/.hunter/_Base/Download/Hunter/0.23.34/70287b1
CMake Error at Build/Hunter-prefix/src/Hunter-stamp/download-Hunter.cmake:157 (message):
  Each download failed!

    error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

         --- LOG END ---
         error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

         --- LOG END ---
         error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

         --- LOG END ---
         error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

         --- LOG END ---
         error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

         --- LOG END ---
         error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

         --- LOG END ---

make[2]: *** [Hunter-prefix/src/Hunter-stamp/Hunter-download] Error 1
make[1]: *** [CMakeFiles/Hunter.dir/all] Error 2
make: *** [all] Error 2

[hunter ** INTERNAL **] Build project failed
[hunter ** INTERNAL **] [Directory:/home/SAMSUNG/khaiii]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at cmake/HunterGate.cmake:87 (message):
Call Stack (most recent call first):
  cmake/HunterGate.cmake:97 (hunter_gate_wiki)
  cmake/HunterGate.cmake:346 (hunter_gate_internal_error)
  cmake/HunterGate.cmake:510 (hunter_gate_download)
  CMakeLists.txt:8 (HunterGate)

-- Configuring incomplete, errors occurred!

**Comment by leejineun** [comment]
https://github.com/ruslo/hunter/issues/328

저도 같은 문제였는데, 위 방법으로 해결했습니다.

**Comment by krikit** [comment]
네, hunter 내부에서 libcurl을 이용해 패키지를 다운로드 하는데요, libcurl이 빌드될 때 openssl, zlib 등을 같이 빌드하지 않으면 다운로드가 제대로 수행되지 못하고 위와같은 에러가 발생합니다.

**Comment by gjustin40** [comment]
> bulid 폴더 안에서 cmake ..을 실행했을 때 이러한 오류가 발생합니다.
> 제가 컴퓨터 전공은 아니라서 제 작업 환경이 이게 맞는지 모르겠지만
> GCP vm을 이용하고 있고 ubuntu 16.x 에서 실행했습니다.
> 
> -- [hunter] Initializing Hunter workspace (70287b1ffa810ee4e952052a9adff9b4856d0d54)
> -- [hunter] https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz
> -- [hunter] -> /home/SAMSUNG/.hunter/_Base/Download/Hunter/0.23.34/70287b1
> CMake Error at Build/Hunter-prefix/src/Hunter-stamp/download-Hunter.cmake:157 (message):
> Each download failed!
> 
> ```
> error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
>      status_code: 1
>      status_string: "Unsupported protocol"
>      log:
>      --- LOG BEGIN ---
>      Protocol "https" not supported or disabled in libcurl
> ```
> Closing connection -1
> 
> ```
>      --- LOG END ---
>      error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
>      status_code: 1
>      status_string: "Unsupported protocol"
>      log:
>      --- LOG BEGIN ---
>      Protocol "https" not supported or disabled in libcurl
> ```
> Closing connection -1
> 
> ```
>      --- LOG END ---
>      error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
>      status_code: 1
>      status_string: "Unsupported protocol"
>      log:
>      --- LOG BEGIN ---
>      Protocol "https" not supported or disabled in libcurl
> ```
> Closing connection -1
> 
> ```
>      --- LOG END ---
>      error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
>      status_code: 1
>      status_string: "Unsupported protocol"
>      log:
>      --- LOG BEGIN ---
>      Protocol "https" not supported or disabled in libcurl
> ```
> Closing connection -1
> 
> ```
>      --- LOG END ---
>      error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
>      status_code: 1
>      status_string: "Unsupported protocol"
>      log:
>      --- LOG BEGIN ---
>      Protocol "https" not supported or disabled in libcurl
> ```
> Closing connection -1
> 
> ```
>      --- LOG END ---
>      error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
>      status_code: 1
>      status_string: "Unsupported protocol"
>      log:
>      --- LOG BEGIN ---
>      Protocol "https" not supported or disabled in libcurl
> ```
> Closing connection -1
> 
> ```
>      --- LOG END ---
> ```
> make[2]: *** [Hunter-prefix/src/Hunter-stamp/Hunter-download] Error 1
> make[1]: *** [CMakeFiles/Hunter.dir/all] Error 2
> make: *** [all] Error 2
> 
> [hunter ** INTERNAL **] Build project failed
> [hunter ** INTERNAL **] [Directory:/home/SAMSUNG/khaiii]
> 
> ## ------------------------------ WIKI -------------------------------
> https://github.com/ruslo/hunter/wiki/error.internal
> CMake Error at cmake/HunterGate.cmake:87 (message):
> Call Stack (most recent call first):
> cmake/HunterGate.cmake:97 (hunter_gate_wiki)
> cmake/HunterGate.cmake:346 (hunter_gate_internal_error)
> cmake/HunterGate.cmake:510 (hunter_gate_download)
> CMakeLists.txt:8 (HunterGate)
> 
> -- Configuring incomplete, errors occurred!

**Comment by gjustin40** [comment]
> bulid 폴더 안에서 cmake ..을 실행했을 때 이러한 오류가 발생합니다.
> 제가 컴퓨터 전공은 아니라서 제 작업 환경이 이게 맞는지 모르겠지만
> GCP vm을 이용하고 있고 ubuntu 16.x 에서 실행했습니다.
> 
> -- [hunter] Initializing Hunter workspace (70287b1ffa810ee4e952052a9adff9b4856d0d54)
> -- [hunter] https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz
> -- [hunter] -> /home/SAMSUNG/.hunter/_Base/Download/Hunter/0.23.34/70287b1
> CMake Error at Build/Hunter-prefix/src/Hunter-stamp/download-Hunter.cmake:157 (message):
> Each download failed!
> 
> ```
> error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
>      status_code: 1
>      status_string: "Unsupported protocol"
>      log:
>      --- LOG BEGIN ---
>      Protocol "https" not supported or disabled in libcurl
> ```
> Closing connection -1
> 
> ```
>      --- LOG END ---
>      error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
>      status_code: 1
>      status_string: "Unsupported protocol"
>      log:
>      --- LOG BEGIN ---
>      Protocol "https" not supported or disabled in libcurl
> ```
> Closing connection -1
> 
> ```
>      --- LOG END ---
>      error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
>      status_code: 1
>      status_string: "Unsupported protocol"
>      log:
>      --- LOG BEGIN ---
>      Protocol "https" not supported or disabled in libcurl
> ```
> Closing connection -1
> 
> ```
>      --- LOG END ---
>      error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
>      status_code: 1
>      status_string: "Unsupported protocol"
>      log:
>      --- LOG BEGIN ---
>      Protocol "https" not supported or disabled in libcurl
> ```
> Closing connection -1
> 
> ```
>      --- LOG END ---
>      error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
>      status_code: 1
>      status_string: "Unsupported protocol"
>      log:
>      --- LOG BEGIN ---
>      Protocol "https" not supported or disabled in libcurl
> ```
> Closing connection -1
> 
> ```
>      --- LOG END ---
>      error: downloading 'https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz' failed
>      status_code: 1
>      status_string: "Unsupported protocol"
>      log:
>      --- LOG BEGIN ---
>      Protocol "https" not supported or disabled in libcurl
> ```
> Closing connection -1
> 
> ```
>      --- LOG END ---
> ```
> make[2]: *** [Hunter-prefix/src/Hunter-stamp/Hunter-download] Error 1
> make[1]: *** [CMakeFiles/Hunter.dir/all] Error 2
> make: *** [all] Error 2
> 
> [hunter ** INTERNAL **] Build project failed
> [hunter ** INTERNAL **] [Directory:/home/SAMSUNG/khaiii]
> 
> ## ------------------------------ WIKI -------------------------------
> https://github.com/ruslo/hunter/wiki/error.internal
> CMake Error at cmake/HunterGate.cmake:87 (message):
> Call Stack (most recent call first):
> cmake/HunterGate.cmake:97 (hunter_gate_wiki)
> cmake/HunterGate.cmake:346 (hunter_gate_internal_error)
> cmake/HunterGate.cmake:510 (hunter_gate_download)
> CMakeLists.txt:8 (HunterGate)
> 
> -- Configuring incomplete, errors occurred!

**Comment by gjustin40** [comment]
@leejineun  좋은 정보 감사합니다. 
나와있는대로 설치를 진행했더니 cmake이 작동하지 않습니다.
(전에 cmake을 설치할 때는 작동했는데, 이 경우에는 안 됩니다.)

$ wget https://cmake.org/files/v3.12/cmake-3.12.4.tar.gz
$ cd cmake-3.12.4/
$ ./bootstrap --system-curl
$ make
$ sudo make install

이와 같이 진행했는데, 다 설치하고 재접속하여 cmake을 실행하면
$ cmake
The program 'cmake' is currently not installed. To run 'cmake' please ask your administrator to install the package 'cmake'
이러한 오류가 발생합니다. path 설정은 어떻게 해야되나요?
(which cmake 를 입력해도 아무것도 안 뜹니다. 리눅스를 다뤄본 적이 없어서 어렵네요.)

**Comment by krikit** [comment]
혹시 cmake3 명령어는 되나요? 만약 된다면 cmake3가 있는 위치로 가신 다음, `sudo ln -s cmake3 cmake`라고 링크를 걸어주세요. (cmake 명령이 되어야 python 패키지도 pip를 통해 설치될겁니다.)

그런데 한가지 걱정되는 부분은 --system-curl 옵션을 주고 cmake를 빌드하신 부분인데요. 이렇게 하면 hunter에서 https 프로토콜 사용이 가능한 지 모르겠습니다. (처음의 문제가 다시 발생하지 않을 지..)

**Comment by gjustin40** [comment]
@krikit 죄송합니다. 중간에 서버가 끊긴 것을 생각 못 하고 sudo make install을 실행하지 않았었네요.
마지막까지 해봐야 알겠지만 우선 위 문제는 해결된 것 같습니다.
정말 감사합니다!!

**Comment by gjustin40** [comment]
다음 과정으로 make resource에서도 에러가 발생하네요... 앞 이슈을 통해 해결해보겠습니다.

**Comment by bluermind** [comment]
> [ruslo/hunter#328](https://github.com/ruslo/hunter/issues/328)
> 
> 저도 같은 문제였는데, 위 방법으로 해결했습니다.

동일한 방법을 겪고 있습니다. 위 방법은 시스템 curl을 rebuild하는 방법 또는 cmake자체를 pip을 통하지 않고 설치 하는것 같은데.. 굳이 system curl을 리빌딩 하지 않고 해결할 수 있는 방법 없을까요?

**Comment by krikit** [comment]
@bluermind 

문제는 curl에서 https 프로토콜을 지원하지 않는 것인데요. 시스템 curl이든 커스텀 빌드 curl이든 새로 빌드하지 않고 해결이 가능할 지 모르겠습니다.

이 부분은 hunter 쪽에 직접 문의하는 것이 가장 확실한 답을 얻으실 수 있을 것 같습니다. 도움을 드리지 못해 죄송합니다. ㅠ.ㅠ
