### ISSUE TITLE
pip install . 시 아스키코드 오류

### ISSUE THREAD

**Issue by leejineun** [kakao/khaiii#22]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-oh1p5ix3-build/setup.py", line 78, in <module>
        long_description=readme(),
      File "/tmp/pip-oh1p5ix3-build/setup.py", line 68, in readme
        return open('/khaiii/README.md').read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 18: ordinal not in range(128)

ubuntu : 16.04 
python : 3.6.7
입니다.

이거 오류 해결방법 아시는 분 계신가요? 구글링 해도 딱 맞는 해결방법을 못찾겠네요

**Comment by krikit** [comment]
원인은 아마도 Python의 IO 기본 인코딩이 UTF-8로 설정되지 않아서 나는 오류 같습니다. 두가지 정도를 시도해 볼 수 있겠는데요. 한번 해보시고 잘 되면 알려주시면 감사하겠습니다.

1. `PYTHONIOENCODING=UTF-8 sudo pip install .` 이라고 해보시기 바랍니다.

2. `build/package_python/setup.py` 파일을 열어서 `open('/khaiii/README.md').read()` 이 부분을 `open('/khaiii/README.md', encoding='UTF-8').read()`로 수정하고 해보시기 바랍니다.

만약 2번이 잘 된다면 코드에 반영해 두도록 하겠습니다.

**Comment by leejineun** [comment]
인코딩 문제는 2번의 방법으로 잘 해결하였습니다.
