### ISSUE TITLE
Makefile:162: recipe for target 'all' failed

### ISSUE THREAD

**Issue by leejineun** [kakao/khaiii#23]
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
 CMakeFiles/obj_khaiii.dir/build.make:231: recipe for target 'CMakeFiles/obj_khaiii.dir/src/main/cpp/khaiii/khaiii_dev.cpp.o' failed
 make[2]: *** [CMakeFiles/obj_khaiii.dir/src/main/cpp/khaiii/khaiii_dev.cpp.o] Error 4
 c++: internal compiler error: Killed (program cc1plus)
 Please submit a full bug report,
 with preprocessed source if appropriate.
 See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
 CMakeFiles/obj_khaiii.dir/build.make:166: recipe for target 'CMakeFiles/obj_khaiii.dir/src/main/cpp/khaiii/Sentence.cpp.o' failed
 make[2]: *** [CMakeFiles/obj_khaiii.dir/src/main/cpp/khaiii/Sentence.cpp.o] Error 4
 c++: internal compiler error: Killed (program cc1plus)
 Please submit a full bug report,
 with preprocessed source if appropriate.
 See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
 CMakeFiles/obj_khaiii.dir/build.make:218: recipe for target 'CMakeFiles/obj_khaiii.dir/src/main/cpp/khaiii/khaiii_api.cpp.o' failed
 make[2]: *** [CMakeFiles/obj_khaiii.dir/src/main/cpp/khaiii/khaiii_api.cpp.o] Error 4
 CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/obj_khaiii.dir/all' failed
 make[1]: *** [CMakeFiles/obj_khaiii.dir/all] Error 2
 Makefile:162: recipe for target 'all' failed
 make: *** [all] Error 2
 Traceback (most recent call last):
   File "<string>", line 1, in <module>
   File "/tmp/pip-mexjgnop-build/setup.py", line 95, in <module>
     cmdclass={'build': CustomBuild}
   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
     dist.run_commands()
   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
     self.run_command(cmd)
   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
     cmd_obj.run()
   File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
     return orig.install.run(self)
   File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
     self.run_command('build')
   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
     self.distribution.run_command(command)
   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
     cmd_obj.run()
   File "/tmp/pip-mexjgnop-build/setup.py", line 50, in run
     subprocess.check_call('make -j all resource', cwd=build_dir, shell=True)
   File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
     raise CalledProcessError(retcode, cmd)
 subprocess.CalledProcessError: Command 'make -j all resource' returned non-zero exit status 2.

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-mexjgnop-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).
read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2d9iydhc-record/install-record.txt --single-version-externally-managed --compile" fa
iled with error code 1 in /tmp/pip-mexjgnop-build/

pip install . 실행시 위와 같은 오류가 발생하는데,  구글 찾아봐도 잘 안나오네요 ㅜㅜ

우분투 : 16.04 입니다

**Comment by krikit** [comment]
혹시 python 패키지 설치 전에 `build` 디렉토리에서 `cmake ..` 한 다음 `make all` 및 `make resource`가 성공적으로 되나요?

참고: https://github.com/kakao/khaiii/blob/master/doc/setup.md

**Comment by leejineun** [comment]
root@master:/khaiii/build/share/khaiii# ls
cnv2hdn.lin  conv.3.fil  embed.bin     errpatch.val  preanal.val  restore.val
config.json  conv.4.fil  errpatch.len  hdn2tag.lin   restore.key
conv.2.fil   conv.5.fil  errpatch.tri  preanal.tri   restore.one

build에서 make resource 후, share/khaiii에 다음과 같이 생성되어있습니다.

bin, test, lib 모두 정상적으로 다운되어있습니다. test도 성공했습니다 ㅜ

**Comment by krikit** [comment]
1) `build/package_python/setup.py` 파일의 `subprocess.check_call('make -j all resource', cwd=build_dir, shell=True)` 부분의 "-j"를 제거하고 한번 해보실 수 있을까요?

2) 만약 1)도 결과가 같다면 `build/package_python` 디렉토리에서 `python3 setup.py build`라고 해보시고 출력 내용을 좀 알려주실 수 있을까요?

**Comment by leejineun** [comment]
1로 해본 결과, 성공했습니다. 정말 감사합니다.

**Comment by krikit** [comment]
다행이네요. "-j" 옵션은 여러 프로세스에서 동시에 빌드를 수행하는건데, 어떤 환경에서는 잘 안되나 보네요. 이 부분도 좀 느리더라도 안전하게 옵션을 빼도록 하겠습니다.
