### ISSUE TITLE
cmake .. 에서 발생하는 hunter 오류 질문입니다

### ISSUE THREAD

**Issue by hongyaegwon** [kakao/khaiii#29]
C:\Users\Yae Gwon\khaiii\build>cmake ..
-- [hunter] Initializing Hunter workspace (70287b1ffa810ee4e952052a9adff9b4856d0d54)
-- [hunter]   https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz
-- [hunter]   -> C:/.hunter/_Base/Download/Hunter/0.23.34/70287b1
지정된 파일을 찾을 수 없습니다
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/nologo"

[hunter ** INTERNAL **] Build project failed
[hunter ** INTERNAL **] [Directory:C:/Users/Yae Gwon]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at cmake/HunterGate.cmake:87 (message):
Call Stack (most recent call first):
  cmake/HunterGate.cmake:97 (hunter_gate_wiki)
  cmake/HunterGate.cmake:346 (hunter_gate_internal_error)
  cmake/HunterGate.cmake:510 (hunter_gate_download)
  CMakeLists.txt:8 (HunterGate)

-- Configuring incomplete, errors occurred!

위와 같은 오류가 발생하는데

아무리 구글링을 해봐도 모르겠습니다..

환경변수를 잘못 설정한 것인지 hunter라는걸 사용해보지 않아서 잘 모르겠습니다..

도와주시면 감사하겠습니다!!

**Comment by hubert-lee** [comment]
@hongyaegwon 
hunter에서 `nmake`를 호출하는 것 같은데, 현재 시스템에 설치되어 있지 않은 듯 합니다.
참고로, hunter와 cmake는 윈도우 환경을 지원하지만, khaiii는 윈도우를 지원하지 않습니다.
이런저런 설정 변경으로 빌드에 성공한다고 하더라도, 올바른 동작을 보장하지 않습니다.

**Comment by hongyaegwon** [comment]
@hubert-lee 
아 운영체제 확인을 안했네요..
감사합니다!
