### ISSUE TITLE
카이 메서드 설명부탁드립니다.

### ISSUE THREAD

**Issue by Gyumyeon** [kakao/khaiii#34]
예시에 나온 Analysis 메서드 말고는 다른 메서드에 대한 정보가 궁금합니다.

**Comment by krikit** [comment]
우선 API들에 대한 충분한 정보를 드리지 못해 죄송합니다. 문서를 만들지 못해 아직 부족한 점이 많습니다.

사실 형태소 분석기는 입력된 텍스트에 대해 형태소 분석 결과를 반환하는 것이 주 기능인 간단한 모듈입니다. (물론 내부는 그리 간단하지 않습니다만..)

Python 바인딩을 기준으로 간단히 한번 설명을 드려보겠습니다.
* analyze: 원문을 입력으로 형태소 분석 결과를 반환하는 메서드
* open / close: 리소스를 열거나 닫는 메서드
* version: 버전 문자열을 반환하는 메서드
* set_log_level / set_log_levels: 로그 레벨을 설정하는 메서드 (trace, debug, info, warn, err, critical)
* analyze_bfr_errpatch: 내부에서 오분석 패치 자동 추출을 위해 사용하는 개발용 API이니 사용하지 마시기 바랍니다.

각 argument와 리턴 값에 대한 내용은 khaiii.py 코드의 주석을 보시거나, python에서 아래와 같이 하시면 간단하게나마 보실 수 있습니다.

```python
>>> import khaiii
>>> help(khaiii.KhaiiiApi)
Help on class KhaiiiApi in module khaiii:

class KhaiiiApi(builtins.object)
 |  khaiii API 객체
 |
 |  Methods defined here:
 |
 |  __del__(self)
 |
 |  __init__(self, lib_path:str='')
 |      Args:
 |          lib_path:  (shared) 라이브러리의 경로
 |
 |  analyze(self, in_str:str, opt_str:str='')
 |      khaiii_analyze() API
 |      Args:
 |          in_str:  입력 문자열
 |          opt_str:  동적 옵션 (JSON 포맷)
 |      Returns:
 |          분셕 결과. 어절(KhaiiiWord) 객체의 리스트
 |
...
```

**Comment by Gyumyeon** [comment]
답변감사합니다
