### ISSUE TITLE
카이가 스파크에 올려질수 있나요?

### ISSUE THREAD

**Issue by Gyumyeon** [kakao/khaiii#37]
카이가 스파크에 올려질수 있나요?

**Comment by krikit** [comment]
scala 혹은 java 환경이라면 아직 불가능합니다만, pyspark 이라면 가능할 것 같습니다.

khaiii.py 모듈이 있는 디렉토리에 lib/libkhaiii.so 및 share/khaiii 디렉터리(리소스 디렉터리)가 있으면 동작하므로, `--files` 혹은 `--archives` 옵션을 잘 사용하시면 될 것 같습니다.
