### ISSUE TITLE
make resource 에서 오류 발생

### ISSUE THREAD

**Issue by KimDoUn** [kakao/khaiii#5]
오류
```
 File "./bin/compile_model.py", line 40
    file_path = f'{rsc_src}/{model_size}.config.json'
                                                    ^
SyntaxError: invalid syntax

Makefile:37: '/home/storage/build/khaiii/build/share/khaiii/config.json' 타겟에 대한 명령이 실패했습니다
make[4]: *** [/home/storage/build/khaiii/build/share/khaiii/config.json] 오류 1
CMakeFiles/resource.dir/build.make:57: 'CMakeFiles/resource' 타겟에 대한 명령이 실패했습니다
make[3]: *** [CMakeFiles/resource] 오류 2
CMakeFiles/Makefile2:284: 'CMakeFiles/resource.dir/all' 타겟에 대한 명령이 실패했습니다
make[2]: *** [CMakeFiles/resource.dir/all] 오류 2
CMakeFiles/Makefile2:291: 'CMakeFiles/resource.dir/rule' 타겟에 대한 명령이 실패했습니다
make[1]: *** [CMakeFiles/resource.dir/rule] 오류 2
Makefile:275: 'resource' 타겟에 대한 명령이 실패했습니다
make: *** [resource] 오류 2
```

----------------------------------------------------------------------------------------------------------------
make all 까지 100% 진행이 다 되고 
bin/khaiii 생성되고
build/khaiii/share/khaiii 폴더 밑에는 아무것도 없습니다.

파이썬 버전과 requirement에 버전은 전부 확인했는데 이상없었습니다.

환경은 linux, docker container 내부에서 git clone하여 실행시켰습니다.

**Comment by Ella77** [comment]
I got similar error but with no syntax error 

Traceback (most recent call last):
  File "./bin/compile_model.py", line 23, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Makefile:37: recipe for target '/home/khaiii/build/share/khaiii/config.json' failed
make[4]: * [/home/khaiii/build/share/khaiii/config.json] Error 1
CMakeFiles/resource.dir/build.make:57: recipe for target 'CMakeFiles/resource' failed
make[3]: * [CMakeFiles/resource] Error 2
CMakeFiles/Makefile2:279: recipe for target 'CMakeFiles/resource.dir/all' failed
make[2]: * [CMakeFiles/resource.dir/all] Error 2
CMakeFiles/Makefile2:286: recipe for target 'CMakeFiles/resource.dir/rule' failed
make[1]: * [CMakeFiles/resource.dir/rule] Error 2
Makefile:275: recipe for target 'resource' failed
make: * [resource] Error 2

**Comment by k2hyun** [comment]
@KimDoUn f-string 포맷에서 invalid syntax 오류가 나오는 것을 보면 python 버전이 3.6 이하인 것 같습니다.

**Comment by k2hyun** [comment]
@Ella77 You have to install pytorch by running ```pip install -r requirements.txt``` before make resource

**Comment by likejazz** [comment]
@Ella77 Just use the provided docker file in `/docker` directory.
```
$ cd docker
$ docker build . -t khaiii
$ docker run -it khaiii /bin/bash
$ bin/khaiii --rsc_dir=share/khaiii/  # Inside a Docker
```

**Comment by cynthia** [comment]
String literals in Python are a relatively new feature, and unless you have full control over the stack involved it seems like a rather risky thing to use - in particular it doesn't seem like a great fit for a open source library.

Considering that a significant chunk of the academic community is still stuck on Python 2, would be nice to fix.

This doesn't seem like a complex issue to fix, unless significant parts of the resource build pipeline has unicode-isms. (expecting str types to be unicode, rather than bytestring)

Is that the case?
