### ISSUE TITLE
기분석 사전만 make resource 후 python은 적용이 안됩니다.

### ISSUE THREAD

**Issue by bdhwan** [kakao/khaiii#50]
기분석 사전을 추가 후 make resource 하면 
명령어로는 추가한 사전이 잘 나오는데 
python으로는 갱신이 안됩니다. 

환경은 docker 환경에서 dockerfile을 그대로 이용하였습니다.

**Comment by krikit** [comment]
#44 #45 이슈에 제가 답변을 단 내용을 한번 참고해 보시기 바랍니다.

**Comment by bdhwan** [comment]
네 리소스폴더의 위치가 달라서 그랬던 것 같습니다. Dockerfile에 있는 그대로 이용하였을 때 
파이썬 소스에서 
from khaiii import KhaiiiApi
api = KhaiiiApi(rsc_dir='/workspace/khaiii/build/share/khaiii')
rsc_dir를 지정해주니 잘 적용되었습니다. 
고맙습니다.
