### ISSUE TITLE
make resource 가 동작을 안합니다.

### ISSUE THREAD

**Issue by bdhwan** [kakao/khaiii#51]
기분석사전 파일 preanal.manual2 파일을 추가하고 
make resource를 하면 어떤 경우는 동작하는데

아래 한문장만 나오고 동작하지 않는 경우가 있습니다. 
Built target resource
원인이 무엇일까요?

**Comment by krikit** [comment]
1) 파일을 추가했음에도 빌드가 되지 않는 경우
    기분석사전 결과물인 `preanal.tri`와 `preanal.val` 파일은 원본인 `preanal.auto` 및 `preanal.manual` 파일보다 최신 파일일 경우 의존성에 의해 굳이 빌드를 하지 않습니다. 이는 Makefile의 특성인데요, 이 부분은 손을 봐야할 것 같습니다.
    이런 경우라면 임시 방편으로 `make clean`으로 기존 빌드된 리소스를 삭제하고 다시 빌드하시면 됩니다.

2) 뭔가 동작하는 것 같은데 프롬프트가 뜨지 않는 경우
    빌드 스크립트 내에서 무한루프같은 오동작이 의심된다면, 아무래도 데이터를 제가 직접 돌려봐야 원인을 알 수 있을 것 같습니다. 혹시 괜찮으시다면 `preanal.manual1` 파일을 첨부해 주실 수 있으실까요?

**Comment by bdhwan** [comment]
1. 파일을 추가했음에도 빌드가 되지 않는 경우
->preanal.tri, preanal.val 을 삭제 후 make resource 하니 잘 되네요
2. 뭔가 동작하는 것 같은데 프롬프트가 뜨지 않는 경우
->별내용없는 파일이었습니다. 
해결 도와주셔서 감사합니다
