### ISSUE TITLE
리눅스나 맥에서만 정상 작동된다는 사실을 명시해주시는게 어떨까요? 

### ISSUE THREAD

**Issue by computerphilosopher** [kakao/khaiii#53]
어제 윈도우 파워쉘로 빌드를 하려다가 실패를 했는데요.

지난 이슈들을 검색해보니 저 말고도 같은 시도를 하셨던 분들이 있는 듯 합니다.

cmake, gcc 등의 툴이 윈도우에서도 쓸 수 있다보니 문서를 읽을 때에는 윈도우에서 작동되지 않을거라는 생각이 들지 않았습니다.

빌드 및 실행 문서나 readme에 명시해주시면 안 될까요?

**Comment by krikit** [comment]
네. 그렇게 하겠습니다. 불편을 끼쳐 드렸다면 죄송합니다.

**Comment by computerphilosopher** [comment]
감사합니다
