### ISSUE TITLE
ModuleNotFoundError 발생

### ISSUE THREAD

**Issue by thisisiron** [kakao/khaiii#56]
windows에서 우분투 앱을 사용해서 해보고 있는데(Windows에서 안 된다고 해주셨지만 우분투앱으로 가능한지 궁금해서...) Import 과정에서 다음과 같은 오류가 발생합니다.

`ModuleNotFoundError: No module named 'khaiii.munjong'`

```
echo $PYTHONPATH
/mnt/c/User/solugate/Desktop/test/khaiii/src/main/python
```

OS: Windows10
UbuntuApp: Ubuntu 18.04.1 LTS
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Python 3.6.7

**Comment by thisisiron** [comment]
PTYHONPATH 설정 오류였습니다.

**Comment by LeeNajeong** [comment]
안녕하세요,
오래된 글이지만 저도 똑같은 오류가 떠서 어떻게 해결하셨는지 여쭙고자 댓글 남깁니다.
