### ISSUE TITLE
형태소 합성 관련

### ISSUE THREAD

**Issue by hkhpub** [kakao/khaiii#57]
안녕하세요
형태소 합성, 즉 분석된 형태소 열을 원문장으로 복원하는 방법이 궁금한데요
혹시 참고할만한 방법이나 프로그램을 알려주시면 감사하겠습니다.

**Comment by krikit** [comment]
형태소 분석기를 학습할 때 입력은 원문이고 출력은 형태소 분석 열입니다. 입력과 출력을 뒤집어 모델을 만들면 어느정도 가능할 것 같습니다. 하지만 이런 쪽으로 연구해본 적이 없어서 구체적인 조언을 드리기는 힘들 것 같습니다.

**Comment by hkhpub** [comment]
@krikit 답변 감사합니다!
