### ISSUE TITLE
Cmake Error version 3.51

### ISSUE THREAD

**Issue by toomy0toons** [kakao/khaiii#6]
`cmake ..
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.10 or higher is required.  You are running version 3.5.1`

3.51 버전에서 make 가 안됩니다.

**Comment by krikit** [comment]
사실 아주 간편한 방법이 있더군요. pip를 통해 cmake 설치가 가능합니다.

```
pip install cmake
```

이렇게 하면 cmake 최신 버전인 3.13 버전이 설치됩니다. 추후 requirements.txt 파일에 추가하고 설치 문서에도 추가해 놓도록 하겠습니다.
