### ISSUE TITLE
문의 드립니다.

### ISSUE THREAD

**Issue by haha23h** [kakao/khaiii#60]
한 문장에서 api.analyze 를 통해 명사만 뽑고 싶은데..방법이 있을런지요?
질문을 어디에 하는지 몰라 여기에 문의 드립니다.

**Comment by krikit** [comment]
아래 링크의 품사 태그표를 참고하셔서 필요한 태그를 필터링 하시면 됩니다.
https://github.com/kakao/khaiii/wiki/%EC%BD%94%ED%8D%BC%EC%8A%A4#%ED%92%88%EC%82%AC-%EC%A7%91%ED%95%A9

만약 일반명사(NNG)와 고유명사(NNP)만 뽑는다면 아래와 같은 코드가 될 것 같습니다.
```python
from khaiii import KhaiiiApi
api = KhaiiiApi()
for word in api.analyze('김대중 대통령은 노벨상을 수상했습니다.'):
    for morph in word.morphs:
        if morph.tag in ['NNG', 'NNP']:
            print(morph.lex)
```

출력은 아래 처럼 나옵니다.
```
김대중
대통령
노벨상
수상
```

**Comment by haha23h** [comment]
감사합니다!
