### ISSUE TITLE
사용자 사전 추가시 중복 문제 발생

### ISSUE THREAD

**Issue by pparksso0308** [kakao/khaiii#63]
![image](https://user-images.githubusercontent.com/35838519/57793685-e39edc80-777c-11e9-9d42-dc387e30edae.png)

 사용자 사전을 추가할 때 preanal.auto 파일에 있는 단어들과 중복될 경우 오류가 발생합니다.
사용자가 추가한 사전에 우선 순위를 줄 수 있는 방법은 없나요?

**Comment by krikit** [comment]
중복된 key에 대해 value가 다른 경우 한쪽을 선택해야 하는 상황으로 보고 의도적으로 오류가 나도록 했습니다.

"preanal." 으로 시작하는 이름의 모든 파일을 합쳐서 사용하게 되므로 파일 별로 우선순위를 두지는 않았습니다. 따라서 현재로서는 우선순위 파일을 지정하는 방법은 없습니다.

외부에서 만든 대량의 사전을 넣고자 할 경우, `preanal.auto`의 내용을 미리 참고하셔서 원하는 우선순위로 제작하시는 것이 좋을 것 같습니다.

**Comment by pparksso0308** [comment]
답변 감사합니다!!
