### ISSUE TITLE
python package에서 large_resource 사용

### ISSUE THREAD

**Issue by bestend** [kakao/khaiii#69]
먼저 khaiii 형태소 분석기를 매우 잘 쓰고 있으며
훌륭한 모듈을 오픈소스로 공개해주신것에 감사드립니다.

현재 package_python을 설치시 resource가 기본으로 고정되어있는데 
옵션으로 large_resource를 선택할수 있게 지원 부탁드립니다.

https://github.com/kakao/khaiii/blob/master/src/main/python/setup.py.in#L50

감사합니다^^

**Comment by krikit** [comment]
네. 현재는 `make package_python` 후 생성되는 setup.py 파일에서 위에 말씀하시는 `make all resource`가 아니라 `make all large_resource`로 수정한 후 `pip install .` 명령을 실행하면 됩니다.

pip 명령에서 리소스를 구분하여 설치할 수 있는 옵션이나 방법이 있는 지 알아보고 다음 버전에서 반영하도록 하겠습니다.
