### ISSUE TITLE
good enough

### ISSUE THREAD

**Issue by skyer9** [kakao/khaiii#75]
매우 잘 작동하네요.
속도 느린 건 다른 방식으로 해결하면 되고, Production 에 그대로 써도 될 성능이네요.

아래 버그는...
어거지로 찾은 버그인데... 모르실 수 있으니까요.
함 봐주시면 좋을 것 같네요.

```sh
cat input.txt 
진짜 더운 한여름제외하고는 다 자주 입어질것같아요~
skyer9@notebook:~/work/gitrepo/khaiii/build$ khaiii --input input.txt 
......
진짜	진짜/MAG
더운	덥/VA + ㄴ/ETM
한여름제외하고는	한/XPN + 여름제외/NNG + 하/XSV + 고/EC + 는/JX
다	다/MAG
자주	자주/MAG
입어질것같아요~	입/VV + 어/EC + 지/VX + ㄹ/ETM + 것/NNB + 같/VA + 아요/EC + ~/SO
```

여튼, 좋은 툴 감사히 잘 쓰겠습니다.

**Comment by krikit** [comment]
우선 아직 부족한 khaiii를 좋아해 주시니 감사 드립니다.

말씀하신 버그는 아래 오분석을 말씀하시는 건가요?
```
한여름제외하고는	한/XPN + 여름제외/NNG + 하/XSV + 고/EC + 는/JX
```

형태소 분석기는 필연적으로 오분석을 만나게 되어 있습니다. 적확도가 95%라는 말은 5%는 오류라는 말이니까요.
그래서 오분석을 "버그"라고 하신다면 좀 가혹한 표현이신 듯 합니다. ^^;

**Comment by skyer9** [comment]
헙. 죄송합니다.
개발자라 원하는 결과가 안나오면 버그라는 단어밖에 생각을 못해서요.

여튼, 원하는 결과를 만들어 줄 한글 형태소 분석기를 쓸 수 있게 된 것에 감사합니다.
