### ISSUE TITLE
사전 빌드 후 python에서 사용시 질문 드립니다

### ISSUE THREAD

**Issue by mirazer0** [kakao/khaiii#76]
기분석 사전 빌드 후
$ ./bin/khaiii --rsc-dir=./share/khaiii
를 이용해 테스트를 하면 사전이 잘 들어간 것으로 나옵니다

근데
python에서 
from khaiii import KhaiiiApi
api = KhaiiiApi()
for word in api.analyze('사전에 등록한 단어'):
    print(word)
이렇게 사전이 잘 들어갔나 확인을 해보면 적용되어있지 않은 것으로 나옵니다.

그래서 다음과 같이 python에 khaiii를 재설치 했습니다
make resource
make install
make package_python
cd package_python
pip install .
재설치를 하면 사전이 적용이 됩니다.

python에 재설치를 해야 적용이 되는건가요 아니면 재 설치 환경이 달라서 그런것일까요
khaiii 사용한다고 파이썬을 처음 써봐서 잘 몰라서 질문드립니다.

**Comment by krikit** [comment]
아래 문서를 참고하시기 바랍니다.
https://github.com/kakao/khaiii/wiki/%EC%84%A4%EC%B9%98-%EC%9C%84%EC%B9%98%EC%97%90-%EA%B4%80%ED%95%98%EC%97%AC

**Comment by mirazer0** [comment]
최고십니다

**Comment by mirazer0** [comment]
링크 올려주신 곳 보고 해결했습니다

build 위치에서 make resource를 하게되면
설치경로/build/share/khaiii 하위에 preanal.tri, preanal.val 파일이 생성 되고
api = KhaiiiApi('/lib/python3.6/site-packages/khaiii/lib/libkhaiii.so', '설치경로/khaiii/build/share/khaiii')

이런식으로 api를 불러오면 사전이 잘 적용 됩니다

**Comment by ZiminPark** [comment]
기분석 사전 위키에 위 내용이 추가되었으면 좋겠습니다!

**Comment by krikit** [comment]
@ZiminPark 

추가했습니다. 조언 감사드립니다.
https://github.com/kakao/khaiii/wiki/%EA%B8%B0%EB%B6%84%EC%84%9D-%EC%82%AC%EC%A0%84#%EC%82%AC%EC%A0%84-%EB%A1%9C%EB%94%A9
