### ISSUE TITLE
파이썬에서 형태소를 딕셔너리 형태로 뽑는 방법이 없을까요?

### ISSUE THREAD

**Issue by dduzzi** [kakao/khaiii#82]
안녕하세요, 파이썬 초보라 그런데 khaiii를 이용하여 형태소 분석을 해보고 싶습니다.

파이썬에 빌드 및 설치까지 했고 정상 작동한것 까지 확인을 했는데

konlpy의 나와있는것 처럼 (에컨데 twitter.pos(문장) ) 형태소 리스트를 뽑아 워드클라우드로 만들려고 합니다.

혹시 형태소를 딕셔내리 형태로 뽑는 방법은 없을까요?

**Comment by krikit** [comment]
KoNLPy와 인터페이스를 맞추는 작업은 성능이 어느정도 개선되고 진행하려 했는데요.. ^^;

다음과 같은 방법으로 사용하시면 될 것 같습니다.

```python3
morphs = []
for word in api.analyze('원하는 문장을 넣으세요.'):
    for morph in word.morphs:
        morphs.append((morph.lex, morph.tag))
pprint(morphs)
```

```
[('원하', 'VV'),
 ('는', 'ETM'),
 ('문장', 'NNG'),
 ('을', 'JKO'),
 ('넣', 'VV'),
 ('으시', 'EP'),
 ('어요', 'EF'),
 ('.', 'SF')]
```

혹은 더 간단하게,
```python3
morphs = [(morph.lex, morph.tag) for word in api.analyze('원하는 문장을 넣으세요.') for morph in word.morphs]
```

이렇게 하시면 됩니다.

**Comment by dduzzi** [comment]
아앗! 감사합니다. 이제보니 딕셔너리 형태가 아니라 리스트 형태였군요 ㅠㅠ
찰떡같이 이해해주셔서 감사합니당!

카카오 충성충성충성
