### ISSUE TITLE
리눅스에서 인터넷없이 설치할 수 있나요?

### ISSUE THREAD

**Issue by socrat8** [kakao/khaiii#83]
crntos7에서 카카오형태소를 설치하는 중입니다.
인터넷을 연결하고 설치할 때는 잘 되는데,
인터넷 연결을 끊고, 설치하니까 중간에 안되는데 될 수 있는 방법이 있나요?

**Comment by krikit** [comment]
khaiii에서 사용하는 여러 의존 패키지들이 [hunter](https://github.com/ruslo/hunter)라는 패키지 관리자를 이용합니다. hunter는 github을 통해 의존 패키지들을 손쉽게 다운로드 및 빌드를 지원해 주는 cmake용 패키지 관리자 입니다.

그리고 pip를 이용해 python 바인딩을 설치하므로 또한 인터넷 연결이 반드시 필요합니다.

그래서 khaiii를 설치하기 위해서는 반드시 인터넷 연결이 되어 있어야 빌드가 가능합니다. 그러나 khaiii가 동작하기 위해 어떤 파일들이 필요한지는 [설치 위치에 관하여](https://github.com/kakao/khaiii/wiki/%EC%84%A4%EC%B9%98-%EC%9C%84%EC%B9%98%EC%97%90-%EA%B4%80%ED%95%98%EC%97%AC) 문서를 보시면 알 수 있으실 겁니다.

따라서, 설치하려는 인터넷이 불가능한 시스템의 환경과 동일한 인터넷이 가능한 환경에서 빌드하신  후 (가령 도커같은 걸로 만드신 후) 필요한 파일을 목적하는 시스템으로 복사하시는 것이 하나의 방법일 것 같습니다.

**Comment by socrat8** [comment]
감사합니다.
한번 테스트해보겠습니다.

**Comment by krikit** [comment]
@socrat8 
위에 말씀하신 파일들은 명령 프롬프트에서 `khaiii` 프로그램을 실행할 때 필요한 파일들이고요.
python에서 사용하시려면 `site-packages` 디렉터리를 찾아서 조금 다른 파일들을 복사해 줘야 합니다.
