### ISSUE TITLE
출력을 텍스트 파일로 뽑을 수 있을까요?

### ISSUE THREAD

**Issue by donyjjuny** [kakao/khaiii#84]
아니면 단어만 저장하려고 하는데요

**Comment by krikit** [comment]
@donyjjuny 
원하시는 바를 좀 더 구체적으로 말씀해 주실 수 있을까요?
`bin/khaiii` 프로그램의 출력 포맷이 원하는 형태가 아니라는 말씀이세요?
아니면 python에서 khaiii 실행 결과 중 품사태그를 제외한 형태소만 파일로 저장하고 싶으신가요?

**Comment by rumbarum** [comment]
```
from khaiii  import KhaiiiApi
khaiii = KhaiiiApi()
```
