### ISSUE TITLE
도커 관련 문의입니다.

### ISSUE THREAD

**Issue by ChiHoonOH** [kakao/khaiii#85]
이 질문을 여기서 드려도 될까 싶지만 일단 khaiii 관련이라서 질문 올립니다.

제가 이전에 윈도우 docker에서 쓰던걸 그대로 ubuntu:18.04 버전에서 사용하려고 했습니다.

docker run 시에 -it 옵션을 지정해줬음에도 불구하고, linux terminal에 접근하지 않고 바로 khaiii가 실행

되어 버립니다. python 모듈안에서 사용하고 싶었던 것이기에 바로 실행이 되지 않고 linux terminal에 접근 

하는 방법을 알고 싶어 문의 드립니다.

2019년도 초기에 github에 있는 가이드대로 설치한 docker입니다.

**Comment by krikit** [comment]
2019년도 초기라고 말씀하시니 v0.3 버전을 의미하시는 듯 합니다.
이 당시부터 지금(v0.4)까지 Docker 파일은 다음과 같이 단순하게 구성되어 있습니다.

```docker
FROM pytorch/pytorch:latest
MAINTAINER nako.sung@navercorp.com

RUN git clone https://github.com/kakao/khaiii.git
WORKDIR /workspace/khaiii

RUN pip install cython
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN mkdir build
WORKDIR /workspace/khaiii/build

RUN cmake ..
RUN make all
RUN make resource

RUN apt-get update -y
RUN apt-get install -y language-pack-ko
RUN locale-gen en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8
```
[코드 링크](https://github.com/kakao/khaiii/blob/master/docker/Dockerfile)

이 이미지를 빌드하고 가령 다음과 같이 실행하시면 말씀하시는 리눅스 터미널에 접근할 것입니다. (bash 프롬프트)
```bash
cd docker
docker build . -t khaiii
docker run -it khaiii /bin/bash
```

그래서 khaiii가 바로 실행된다는 말씀이 잘 이해가 되지 않습니다. 혹시 마지막에 `docker run`을 실행할 때  `/bin/bash`가 아니라 `./khaiii`와 같이 실행하신 것은 아닌지요?

만약 배포된 v0.3 혹은 v0.4 버전이 아니라 develop 브랜치를 사용하고 계신다면 상황이 또 다를 듯 합니다. 아래 두가지 내용을 좀더 자세히 알려주시면 도움이 될 듯 합니다.
* 도커를 빌드하고 실행중인 khaiii 버전 (혹은 커밋 해쉬)
* 실행하신 도커 명령어

**Comment by ChiHoonOH** [comment]
khaiii를 이름으로 지정한다는게 잘못했네요. 버전 업그레이드 방법까지 알려주셔서 감사합니다.
