### ISSUE TITLE
빌드에서 문제

### ISSUE THREAD

**Issue by limth85** [kakao/khaiii#88]
안녕하세요,
빌드시 cmake .. 를 실행하면

-- [hunter] Initializing Hunter workspace (70287b1ffa810ee4e952052a9adff9b4856d0d54)
-- [hunter]   https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz
-- [hunter]   -> /Users/LiMac/.hunter/_Base/Download/Hunter/0.23.34/70287b1
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

[hunter ** INTERNAL **] Build project failed
[hunter ** INTERNAL **] [Directory:/Users/LiMac/khaiii]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at cmake/HunterGate.cmake:87 (message):
Call Stack (most recent call first):
  cmake/HunterGate.cmake:97 (hunter_gate_wiki)
  cmake/HunterGate.cmake:346 (hunter_gate_internal_error)
  cmake/HunterGate.cmake:510 (hunter_gate_download)
  CMakeLists.txt:8 (HunterGate)

-- Configuring incomplete, errors occurred!

이라는 에러가 뜹니다.
어떻게 해야하나요?

감사합니다!

**Comment by krikit** [comment]
저도 잘은 모르겠습니다만.. 아래를 참고해 보세요.
https://sssunho.tistory.com/64

**Comment by limth85** [comment]
옷!! 성공했습니다!!! 감사합니다!!!!
