### ISSUE TITLE
인물검색 가이드 요청드립니다.

### ISSUE THREAD

**Issue by ynebula** [kakao/khaiii#89]
안녕하세요. Khaiii를 사용하는 중 다음과 같은 문제점이 잇어 문의 드립니다.

"안병의"님의 분석이 다음과 같이 되어 의도와 다른 결과를 내고 있습니다.
> 안병의	안/NNG + 병/NNP + 의/JKG

"안병의"님을 명사로 결과를 도출하기 위한 방법 가이드 부탁드립니다.

**Comment by krikit** [comment]
@ynebula 

[기분석 사전](https://github.com/kakao/khaiii/wiki/%EA%B8%B0%EB%B6%84%EC%84%9D-%EC%82%AC%EC%A0%84)을 이용해 보시면 어떨까요?

**Comment by ynebula** [comment]
답변 감사합니다.

덕분에 해결해결 했습니다.
