### ISSUE TITLE
dockerfile build 오류

### ISSUE THREAD

**Issue by hsh2438** [kakao/khaiii#91]
dockerfile을 그대로 build를 해보려고 했는데, base 이미지인 pytorch 이미지에 git과 gcc가 없어서 오류가 납니다.

아래와 같이 dockerfile을 수정하는 것이 어떨까요?

    FROM pytorch/pytorch:latest

    RUN apt-get update && apt-get install -y git build-essential

    RUN git clone https://github.com/kakao/khaiii.git
    WORKDIR /workspace/khaiii

    RUN pip install -r requirements.txt

    WORKDIR /workspace/khaiii/build

    # build khaiii
    RUN cmake ..
    RUN make all
    RUN make resource
    RUN make install

    # for python binding
    WORKDIR /workspace/khaiii/build/package_python
    RUN pip install .

    # locale setting
    RUN apt-get update && apt-get install -y language-pack-ko
    RUN locale-gen en_US.UTF-8
    RUN update-locale LANG=en_US.UTF-8

**Comment by krikit** [comment]
현재 master 브랜치에 있는 도커 파일은 맨 처음에 다른 분의 도움으로 들어갔던 건데요. #1 
당시에는 latest 이미지를 이용해 빌드를 했는데, 지금의 latest 이미지는 빌드가 되지 않네요.

develop 브랜치에 있는 도커 파일들은 역시 다른 분의 도움으로 여러 버전이 준비되어 있고요. #79 
제가 방금 빌드를 해보니 정상적으로 되는 것을 확인했습니다. 다음 버전의 배포가 이뤄지면 자연스럽게 해결 될 것 같습니다.

v0.4 버전이 배포된지 오래되서 Ubuntu 20.04 버전에서 빌드가 되지 않는 등의 에러가 있는 상황인데요.
v0.5 버전은 모델 개선 후 배포하려 했으나 모델 개선이 좀처럼 잘 되지 않아 배포가 좀 늦어지고 있습니다.
모델 개선 전에 빌드 관련 오류를 수정하여 배포할 것을 고려하고 있으니 조금만 기다려 주시면 감사하겠습니다.

**Comment by hsh2438** [comment]
아하 dev 브랜치에 다른 dockerfile이 또 있네요. 감사합니다.
이슈는 닫겠습니다.
