### ISSUE TITLE
형태소 분석 결과 저장

### ISSUE THREAD

**Issue by yyyoooa** [kakao/khaiii#95]
안녕하세요, 

파이썬 환경에서 khaiii 형태소 분석 실행 결과를 .txt나 .csv 파일로 저장해서 사용하고 싶은데 방법이 따로 있을까요?

**Comment by krikit** [comment]
[Python 바인딩](https://github.com/kakao/khaiii/wiki/%EB%B9%8C%EB%93%9C-%EB%B0%8F-%EC%84%A4%EC%B9%98#python-%EB%B0%94%EC%9D%B8%EB%94%A9) 부분을 보시면 python으로 형태소분석을 하는 예제 코드가 있습니다.

아래와 같은 방법으로 입/출력 파일을 지정해서 사용하시면 될 것 같습니다.
```python3
from khaiii import KhaiiiApi

api = KhaiiiApi()
fout = open('output.txt', 'wt')

for line in open('input.txt', 'rt'):
    for word in api.analyze(line.strip()):
        print(word, file=fout)
```

**Comment by yyyoooa** [comment]
감사합니다!

그런데 위 코드로 실행했더니 텍스트 파일 생성은 되었는데, 전체 분석 결과가 다 저장되지 않고 끝부분이 잘려나갔습니다. 

for line in open('input.txt', 'rt'):
    for word in api.analyze(line.strip()):
        print(word)

로 실행한 결과 창에서는 끝까지 잘 나오는데, 저장된 파일에는 손실된 부분이 있습니다.
이건 개인 컴퓨터의 문제일까요?

**Comment by krikit** [comment]
제가 추가 질문을 놓쳤었네요. 죄송합니다.
말씀하신 문제는 아마도 파일 시스템의 버퍼링 문제 같습니다.
