### ISSUE TITLE
cmake error (hunter)

### ISSUE THREAD

**Issue by Matthew0633** [kakao/khaiii#96]
안녕하세요. ubuntu 20.04에서 khaiii를 설치하는 도중에 cmake .. 를 실행하는 단계에서 에러가 발생하였습니다. hunter와 관련된 것같은데 정확한 원인과 해결책을 스스로 찾기가 어렵습니다. 
cmake는 apt-get을 통해 설치하였고 3.16 버전입니다. 도와주신다면 감사하겠습니다.

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at /root/.hunter/_Base/Download/Hunter/0.23.34/70287b1/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /root/.hunter/_Base/Download/Hunter/0.23.34/70287b1/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  /root/.hunter/_Base/Download/Hunter/0.23.34/70287b1/Unpacked/cmake/modules/hunter_download.cmake:613 (hunter_fatal_error)
  /root/.hunter/_Base/Download/Hunter/0.23.34/70287b1/Unpacked/cmake/projects/GTest/hunter.cmake:244 (hunter_download)
  /root/.hunter/_Base/Download/Hunter/0.23.34/70287b1/Unpacked/cmake/modules/hunter_add_package.cmake:62 (include)
  CMakeLists.txt:63 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "/home/user1/khaiii/build/CMakeFiles/CMakeOutput.log".

**Comment by krikit** [comment]
Ubuntu 20.04에서는 빌드가 되지 않는 현상은 known issue입니다.

1) 슬랙에서 어떤 분이 아래와 같이 warning을 무시하는 형태로 빌드에 성공하셨다고 합니다.
```bash
$ cmake -E env CXXFLAGS="-w" cmake ..
```
제가 환경이 갖춰지지 않아 해보진 않았습니다만, 참고하셔도 좋을 듯 합니다.

2) 혹은 급하신 경우 임시로 18.04에서 빌드하신 후 바이너리를 복사해서 사용해 보시기 바랍니다.

khaiii에서 사용하는 의존 라이브러리들의 버전도 좀 오래 되었고, Ubuntu 20.04 빌드가 되지 않는 문제가 있는데요.
조만간 빌드와 관련된 문제를 해결하여 배포하도록 하겠습니다. 조금만 기다려 주시길 부탁드립니다.

**Comment by Matthew0633** [comment]
말씀대로 18.04에서 설치하였더니 해결되었습니다. 친절하고 신속하게 도와주셔서 감사합니다!

**Comment by duck9667** [comment]
감사합니다!! 하루종일 헤맸는데 해결했네요!

**Comment by eubinecto** [comment]
> Ubuntu 20.04에서는 빌드가 되지 않는 현상은 known issue입니다.
> 
> 1. 슬랙에서 어떤 분이 아래와 같이 warning을 무시하는 형태로 빌드에 성공하셨다고 합니다.
> 
> ```shell
> $ cmake -E env CXXFLAGS="-w" cmake ..
> ```
> 
> 제가 환경이 갖춰지지 않아 해보진 않았습니다만, 참고하셔도 좋을 듯 합니다.
> 
> 2. 혹은 급하신 경우 임시로 18.04에서 빌드하신 후 바이너리를 복사해서 사용해 보시기 바랍니다.
> 
> khaiii에서 사용하는 의존 라이브러리들의 버전도 좀 오래 되었고, Ubuntu 20.04 빌드가 되지 않는 문제가 있는데요. 조만간 빌드와 관련된 문제를 해결하여 배포하도록 하겠습니다. 조금만 기다려 주시길 부탁드립니다. 
너무 감사합니다~~~~ 이거 하나로 해결했네요..허허
